### ISSUE TITLE
Publish to Package Control

### ISSUE THREAD

**Issue by rojepp** [fsharp/sublime-fsharp-package#4]
https://packagecontrol.io/docs/submitting_a_package

This should happen sooner, rather than later. If this is in Package control, it will get more eyes on it, and quality will go up. :)

Package control expects a clean repo with the published bits only. A Fake script could publish the contents of the bin folder to a clean repo. The new repo could be a subrepo here.
When that is ready, a PR should be submitted for Package Control Channel

**Comment by guillermooo** [comment]
Yes, that's the plan. But I'm not sure we need a subrepo. Since a script will interact with the releases-repo, hopefully nobody will need to edit files in the releases-repo by hand? In that case, we can keep both completely separated. (That's what I do with the Dart plugin, for example.)

The package isn't in PC yet because I seem to remember that it's broken. I haven't used it in a while... We first need to ensure that it won't mess up users' ST installation.

**Comment by guillermooo** [comment]
Let's get the current package working on all 3 OSes as it is and then publish it.

**Comment by rojepp** [comment]
I think it is time to publish this. :)

**Comment by guillermooo** [comment]
I think the idea was to publish from a releases-only repo. If we're still going down that path, I'll try to create a repo tonight.

**Comment by guillermooo** [comment]
- [ ] review PC requirements for non .sublime-package packages, etc.

**Comment by rojepp** [comment]
The package name, "FSharp" is fine right? Doesn't collide with anything and follows the naming guideline.

Some points from the guideline
* Try not to use the word Sublime in your package name. 
* Use CamelCase or underscore_notation.
* Do not use a . in the package name. 
* Use ASCII only if possible.

**Comment by rojepp** [comment]
Any other considerations, apart from adding the file '.no-sublime-package' to the root?

**Comment by guillermooo** [comment]
https://github.com/wbond/package_control_channel/pull/4493
